/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.deftech.viewtils.test;

public final class R {
  /* To regenerate ids, run this ruby script:

    path_to_r = "/path/to/src/test/java/org/robolectric/R.java"

    if path_to_r =~ /^\/path\/to/
      raise "please change the path to this file!"
    else
      original_contents = File.read(path_to_r)
      x = 0xffff
      new_contents = original_contents.gsub(/class|0x[0-9a-fA-F]+;/) do |match|
      if match == "class"
        x += 0x100
        x = x & 0xffffff00
        x -= 1
        "class"
      else
        "0x#{"%x" % (x += 1)};"
      end
      end
      File.open(path_to_r, "w") { |f| f << new_contents }
    end

   */


    public static final class id {
        public static final int textView = 0x10000;
        public static final int button = 0x10001;
    }

    public static final class string {
        //public static final int howdy = 0x10100;
    }

    public static final class plurals {
    }

    public static final class array {
    }

    public static final class color {
    }

    public static final class drawable {
    }

    public static final class layout {
        public static final int main_layout = 0x10600;
    }

    public static final class anim {
    }

    public static final class animator {
    }

    public static final class raw {
    }

    public static final class attr {
    }

    public static final class menu {
    }

    public static final class xml {
    }

    public static final class styleable {
    }

    public static final class dimen {
    }

    public static final class integer {
    }

    public static final class bool {
    }

    public static final class style {
    }
}
